[Car]: add controller, service, repository
jv-jun23-team1/car-sharing-app pull request #10
Opened 2023-10-02 18:57 UTC by Someboty

Create CarController with add(), getAll(), getById(), update(), delete() methods
Create CarService and CarServiceImpl with corresponding methods 
Create CarDto and CreateCarDto for data protection 
Create MapperConfig for mapper classes configuration 
Create CarMapper for mapping between CreateCarDto, CarDto and Car objects 
Create CarRepository for DB operations
Create EntityNotFoundException for exceptions related to the absence of corresponding objects in the database

2023-10-02 19:10 UTC, ConfusedSatlan requested changes
Let's improve your solution

2023-10-02 19:10 UTC, ConfusedSatlan commented on src/main/java/com/team01/carsharingapp/service/impl/CarServiceImpl.java
> +            throw new EntityNotFoundException("Can't find book by id: " + id);
change book to car

2023-10-02 20:19 UTC, Someboty commented on src/main/java/com/team01/carsharingapp/service/impl/CarServiceImpl.java
> +        car.setDailyFee(request.dailyFee());
It's not for creating, it's for updating. But I move it to separate method, as you wish.

2023-10-02 20:19 UTC, Someboty commented on src/main/java/com/team01/carsharingapp/service/impl/CarServiceImpl.java
> +            throw new EntityNotFoundException("Can't find book by id: " + id);
My bad

2023-10-03 07:05 UTC, IhorKalaur approved these changes

2023-10-03 07:22 UTC, keda-vlad approved these changes

2023-10-03 07:25 UTC, Someboty commented on src/main/java/com/team01/carsharingapp/service/impl/CarServiceImpl.java
> +    private void updateValues(Car car, CreateCarRequestDto request) {
Cannot resolve symbol 'builder'

2023-10-03 08:07 UTC, ConfusedSatlan approved these changes

2023-10-03 08:07 UTC, merged