[APP]: add readme file
jv-jun23-team1/car-sharing-app pull request #36
Opened 2023-10-05 16:47 UTC by Someboty

First version of README

2023-10-05 16:56 UTC, ConfusedSatlan requested changes

2023-10-05 16:56 UTC, ConfusedSatlan commented on README.md
> +| PaymentController        | Create a new payment, get all payments by user ID                                                   | -                                    |
Manager can get all payments of users

2023-10-05 17:19 UTC, Denis-Balako reviewed
Left some suggestions

2023-10-05 17:19 UTC, Denis-Balako commented on README.md
> +- [Roles](#roles)
add emoji

2023-10-05 17:19 UTC, Denis-Balako commented on README.md
> +docker build -t {your-image-name}
```suggestion
docker build -t {your-image-name} .
```

2023-10-05 17:27 UTC, Someboty commented on README.md
> +- [Roles](#roles)
Where did you get them?

2023-10-06 06:22 UTC, keda-vlad approved these changes

2023-10-06 07:05 UTC, Denis-Balako approved these changes

2023-10-06 07:06 UTC, merged